### ISSUE TITLE
When duplicate relations are available, and the second one has an error, the marker is shown on the first

### ISSUE THREAD

**Issue by rhamzeh** [openfga/language#93]
<img width="587" alt="Screen Shot 2022-09-29 at 11 53 52 AM" src="https://user-images.githubusercontent.com/536147/193145371-cbd2d9d6-df0c-4373-83cb-db615197f637.png">

**Comment by d-jeffery** [comment]
Duplicate relation errors have been addressed.

Presentation;

![image](https://github.com/user-attachments/assets/fcee71f6-2f14-4f71-b078-4f6aababc604)

<img width="583" alt="image" src="https://github.com/user-attachments/assets/c5462a8d-49b9-4942-8dde-43482dc35526">

[Example test](https://github.com/openfga/language/blob/63dea5d54b1394e80386a9a2bbc37ef3995bfcd4/tests/data/dsl-syntax-validation-cases.yaml#L323-L342)

Example test:

https://github.com/openfga/language/blob/63dea5d54b1394e80386a9a2bbc37ef3995bfcd4/tests/data/dsl-syntax-validation-cases.yaml#L323-L342


Link to validation code: 

https://github.com/openfga/language/blob/63dea5d54b1394e80386a9a2bbc37ef3995bfcd4/pkg/js/transformer/dsltojson.ts#L209-L216
