### ISSUE TITLE
Syntax error on last line reporting empty range from `checkDSL`

### ISSUE THREAD

**Issue by d-jeffery** [openfga/language#95]
One error I'm encountering;

![image](https://github.com/openfga/syntax-transformer/assets/1425457/833eff14-a7a9-4808-8db6-233e4af5774d)

If I make an error here like in the attached screenshot (removing a closing bracket on the last line), it reports an invalid range. I get the following error contents;
```
{
  severity: 8,
  startColumn: 0,
  endColumn: 0,
  startLineNumber: 21,
  endLineNumber: 21,
  message: "Invalid syntax",
  source: "linter",
}
```

Right line, but 0s on the start & end cols.

**Comment by rhamzeh** [comment]
@d-jeffery is this still the case or can we close this issue?

**Comment by d-jeffery** [comment]
@rhamzeh can't replicate anymore, so we should be good to cose.

<img width="527" alt="image" src="https://github.com/openfga/language/assets/1425457/881333fb-dbff-4c5a-98df-567536c23397">
